/* 
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/

-- src/lib.rs:24
-- horloge::on_horloge_timers_event
CREATE FUNCTION "on_horloge_timers_event"()
	RETURNS TRIGGER
	LANGUAGE c
	AS 'MODULE_PATHNAME', 'on_horloge_timers_event_wrapper';
