/* 
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/

-- src/lib.rs:22
CREATE SCHEMA IF NOT EXISTS horloge; /* horloge::horloge */

-- src/lib.rs:38
-- horloge::horloge::horloge_timers_before_update
CREATE FUNCTION horloge."horloge_timers_before_update"()
	RETURNS TRIGGER
	LANGUAGE c
	AS 'MODULE_PATHNAME', 'horloge_timers_before_update_wrapper';

-- src/lib.rs:38
-- horloge::horloge::horloge_timers_before_insert
CREATE FUNCTION horloge."horloge_timers_before_insert"()
	RETURNS TRIGGER
	LANGUAGE c
	AS 'MODULE_PATHNAME', 'horloge_timers_before_insert_wrapper';

-- src/lib.rs:38
-- horloge::horloge::horloge_timers_before_delete
CREATE FUNCTION horloge."horloge_timers_before_delete"()
	RETURNS TRIGGER
	LANGUAGE c
	AS 'MODULE_PATHNAME', 'horloge_timers_before_delete_wrapper';

-- src/lib.rs:38
-- horloge::horloge::horloge_timers_after_update
CREATE FUNCTION horloge."horloge_timers_after_update"()
	RETURNS TRIGGER
	LANGUAGE c
	AS 'MODULE_PATHNAME', 'horloge_timers_after_update_wrapper';

-- src/lib.rs:38
-- horloge::horloge::horloge_timers_after_insert
CREATE FUNCTION horloge."horloge_timers_after_insert"()
	RETURNS TRIGGER
	LANGUAGE c
	AS 'MODULE_PATHNAME', 'horloge_timers_after_insert_wrapper';

-- src/lib.rs:38
-- horloge::horloge::horloge_timers_after_delete
CREATE FUNCTION horloge."horloge_timers_after_delete"()
	RETURNS TRIGGER
	LANGUAGE c
	AS 'MODULE_PATHNAME', 'horloge_timers_after_delete_wrapper';

-- src/lib.rs:55
-- horloge::horloge::deactivate_timers
CREATE  FUNCTION horloge."deactivate_timers"(
	"rel" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'deactivate_timers_wrapper';

-- src/lib.rs:49
-- horloge::horloge::activate_timers
CREATE  FUNCTION horloge."activate_timers"(
	"rel" TEXT /* &str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'activate_timers_wrapper';
